### PR TITLE
Merge opencog to singnet

### PR DESCRIPTION
**Pull request by vsbogd**

### CODE REVIEW

**Comment by vsbogd** [comment]
@AmeBel , could you please merge

**Comment by amebel** [comment]
Ok will merge after a fix on  upstream

**Comment by vsbogd** [comment]
@AmeBel , excuse me what fix do you mean? My fix is already in this PR.

**Comment by vsbogd** [comment]
@AmeBel , please dont' merge it see https://github.com/singnet/ocpkg/pull/3

**Pull request closed without merging**
